<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile>
      <!-- Upstream targets VS2019. Current compilers add warnings in unchanged externals. -->
      <TreatWarningAsError>false</TreatWarningAsError>
      <AdditionalIncludeDirectories>$(LocalTeamsD3DX)\build\native\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalOptions>/PDBALTPATH:SlippiLocalTeams.pdb %(AdditionalOptions)</AdditionalOptions>
      <AdditionalLibraryDirectories>$(LocalTeamsD3DX)\build\native\release\lib\x64;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
  </ItemDefinitionGroup>
</Project>
